export const userloginUrl="/api/users/login"
export const userregisterUrl="/api/users/add-user-by-refferal"
export const verifyOtpUrl="/api/users/verify-otp"
export const sendforgototpUrl="/api/users/send-forget-otp"
export const forgotPasswordOtpUrl="/api/users/forget-password-otp"
export const changePasswordUrl="/api/users/change-password"
export const getUserPost="/api/users/get-media"
export const getUserProfile="/api/users/profile"
export const getLatestPosts="/api/posts/get-latest-posts"
export const getSuggestions="/api/users/get-suggestions"
export const followUser="/api/users/follow"
export const unFollowUser="/api/users/unfollow"
export const getProfilePic="/api/users/get-profile-pic"
export const likeAPost="/api/posts/like"
export const uploadImage="/api/users/upload-image"
export const allUsers="/api/users/all-users"
export const getUser="/api/users/get-user/"
export const postComment="/api/posts/post-comment"
export const deleteCommentByCommentOwner="/api/posts/delete-comment/"



